extensions:
  basicauth/opensearch:
    client_auth:
      username: "admin"
      password: "YourSecurePassword123!"
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# processors:
#   batch:

exporters:
  # opensearch:
  #   mapping:
  #     mode: "ss4o"
  #     manage_index_template: false
  #   logs_index: ss4o_logs-test-logs
  #   traces_index: ss4o_traces-test-traces
  #   http:
  #     endpoint: "https://opensearch:9200"
  #     tls:
  #       insecure_skip_verify: true
  #     # Ссылаемся на созданное выше расширение аутентификации
  #     auth:
  #       authenticator: basicauth/opensearch

  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

  otlp/data-prepper:
    endpoint: "data-prepper:21893"
    tls:
      insecure: true

  # Экспортёр: хранение логов в S3-совместимом SeaweedFS
  awss3:
    s3uploader:
      s3_bucket: "otel-archive" # ЗАМЕНА: строго s3_bucket вместо bucket
      region: "us-east-1"
      s3_force_path_style: true
      endpoint: "http://seaweedfs:8333"
      s3_prefix: "logs" # Опциональная папка в бакет

  debug:
    verbosity: normal

service:
  extensions: [basicauth/opensearch, health_check]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/prometheus, otlp/data-prepper]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/data-prepper, debug]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [awss3, debug]
