# Глобальные настройки вывода в консоль
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss,SSS} [%thread] %-5level %logger{36} - %msg%n

# Базовый уровень логирования для всего Data Prepper (INFO)
rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

# ВКЛЮЧАЕМ DEBUG ДЛЯ PEER FORWARDER (Ядро)
logger.peerforwarder_core.name = org.opensearch.dataprepper.core.peerforwarder
logger.peerforwarder_core.level = DEBUG
logger.peerforwarder_core.additivity = false
logger.peerforwarder_core.appenderRefs = stdout
logger.peerforwarder_core.appenderRef.stdout.ref = STDOUT

# ВКЛЮЧАЕМ DEBUG ДЛЯ PEER FORWARDER (Плагины/Процессоры)
logger.peerforwarder_plugins.name = org.opensearch.dataprepper.plugins.processor.peerforwarder
logger.peerforwarder_plugins.level = DEBUG
logger.peerforwarder_plugins.additivity = false
logger.peerforwarder_plugins.appenderRefs = stdout
logger.peerforwarder_plugins.appenderRef.stdout.ref = STDOUT
